# Use an appropriate base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port on which Streamlit runs
EXPOSE 8501

# Command to run the Streamlit application
CMD ["streamlit", "run", "alpha_vantage_3.py"]
